### ISSUE TITLE
ImportError: No module named queue.fqueue

### ISSUE THREAD

**Issue by buriy** [Kronuz/pyXapiand#4]
``` xapiand
Traceback (most recent call last):
  File "/usr/local/bin/xapiand", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/xapiand/__main__.py", line 7, in main
    from xapiand.bin.worker import main
  File "/usr/local/lib/python2.7/dist-packages/xapiand/bin/worker.py", line 17, in <module>
    from xapiand.server import xapiand_run
  File "/usr/local/lib/python2.7/dist-packages/xapiand/server/__init__.py", line 3, in <module>
    from .server import xapiand_run  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/xapiand/server/server.py", line 33, in <module>
    from .queue.fqueue import FileQueue
ImportError: No module named queue.fqueue
```

Started in 2.0.3 and still happens in 2.0.6

**Comment by Kronuz** [comment]
Weird. The module is there in the queue directory... Unless either it cannot be imported or is not included in the PyPI package. At any rate, I remember I removed that module and changed other things in our local pyXapiand. Maybe it's time to sync and make a new release...

We have been working in a C++ version of Xapiand, but it's still a work in progress and it isn't anywhere ready for production yet.

**Comment by buriy** [comment]
I guess it's not in the distribution of setup.py -- 
I haven't found "/usr/local/lib/python2.7/dist-packages/xapiand/queue" folder at all.
I installed the library with pip, if it's relevant.
